=== phinc/PMC/PMC/build/classes/by/phinc/pmc/data/activity.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.phinc.by/pmc/activity" 
		xmlns:act="http://www.phinc.by/pmc/activity" >
	
	<xsd:element name="activities">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="activity" type="act:ActivityType" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="ActivityType">
		<xsd:all>
			<xsd:element name="description" type="xsd:string"/>
			<xsd:element name="start-date" type="xsd:date"/>
			<xsd:element name="duration" type="act:DurationType"/>
			<xsd:element name="reporter">
				<xsd:complexType>
					<xsd:attribute name="employee-id" type="xsd:positiveInteger" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:all>
		<xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
		<xsd:attribute name="assignment-id" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
	
	<xsd:simpleType name="DurationType">
		<xsd:union memberTypes="act:EmptyType act:DecimalType"/>
	</xsd:simpleType>
	
	<xsd:simpleType name="EmptyType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value=""/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="DecimalType">
		<xsd:restriction base="xsd:decimal">
			<xsd:fractionDigits value="1"/>
			<xsd:minExclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== phinc/PMC/PMC/src/by/phinc/pmc/data/activity.xml
<?xml version="1.0"?><act:activities xmlns:act="http://www.phinc.by/pmc/activity" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.phinc.by/pmc/activity activity.xsd">
	<activity id="1" assignment-id="1">
		<description><![CDATA[XML file project.xml was created]]></description>
		<start-date>2012-05-03</start-date>
		<duration>1.5</duration>
		<reporter employee-id="1"></reporter>
	</activity>
	<activity id="2" assignment-id="1">
		<description><![CDATA[XML file assignment.xml was created]]></description>
		<start-date>2012-05-03</start-date>
		<duration>1</duration>
		<reporter employee-id="1"></reporter>
	</activity>
<activity id="4" assignment-id="4">
		<description><![CDATA[bought special creme against inscts]]></description>
		<start-date>2012-06-02</start-date>
		<duration>0.4</duration>
<reporter employee-id="1"></reporter>	</activity>
<activity id="5" assignment-id="10">
		<description><![CDATA[vcxb]]></description>
		<start-date>2003-02-14</start-date>
		<duration>7.0</duration>
	<reporter employee-id="1"></reporter>
	</activity>
</act:activities>
