=== phinc/PMC/PMC/build/classes/by/phinc/pmc/data/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.phinc.by/pmc/document" 
	xmlns:doc="http://www.phinc.by/pmc/document">
	
	<xsd:element name="documents">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="document" type="doc:DocumentType" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
		
	<xsd:complexType name="DocumentType">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string"/>
			<xsd:element name="file-name" type="xsd:string"/>
			<xsd:element name="description" type="xsd:string"/>
			<xsd:element name="path" type="xsd:string"/>
			<xsd:choice>
				<xsd:element name="project" type="doc:IdType" />
				<xsd:element name="task" type="doc:IdType"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="IdType">
		<xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
		
</xsd:schema>

=== phinc/PMC/PMC/build/classes/by/phinc/pmc/data/document.xml
<?xml version="1.0" encoding="UTF-8"?>
<doc:documents xmlns:doc="http://www.phinc.by/pmc/document"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://www.phinc.by/pmc/document document.xsd">
	<document id="1">
		<name><![CDATA[Specification]]></name>
		<file-name>spec1.doc</file-name>
		<description><![CDATA[Software Requirements Specification]]></description>
		<path><![CDATA[c:/temp]]></path>
		<project id="1"/>
	</document>
	<document id="2">
		<name><![CDATA[Specification]]></name>
		<file-name>spec2.doc</file-name>
		<description><![CDATA[Software Requirements Specification]]></description>
		<path><![CDATA[c:/temp]]></path>
		<task id="2"/>
	</document>
</doc:documents>
