=== phinc/PMC/PMC/src/by/phinc/pmc/data/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.phinc.by/pmc/employee" 
	xmlns:emp="http://www.phinc.by/pmc/employee">

	<xsd:element name="employees">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="employee" type="emp:EmployeeType" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="EmployeeType">
		<xsd:all>
			<xsd:element name="first-name" type="xsd:string"/>
			<xsd:element name="last-name" type="xsd:string"/>
			<xsd:element name="email" type="xsd:string"/>
			<xsd:element name="post" type="xsd:string"/>
			<xsd:element name="login" type="xsd:string"/>
			<xsd:element name="password" type="xsd:string"/>
		</xsd:all>
		<xsd:attribute name="id" type="xsd:positiveInteger" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== phinc/PMC/PMC/src/by/phinc/pmc/data/employee.xml
<?xml version="1.0"?><emp:employees xmlns:emp="http://www.phinc.by/pmc/employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.phinc.by/pmc/employee employee.xsd">
	<employee id="1">
		<first-name>Irina</first-name>
		<last-name>Fedortsova</last-name>
		<email>phinc@tut.by</email>
		<post>engineer</post>
		<login>phinc</login>
		<password><![CDATA[123]]></password>
	</employee>
	<employee id="2">
		<first-name>Irina</first-name>
		<last-name>Fedortsova</last-name>
		<email>phinc@tut.by</email>
		<post>engineer</post>
		<login>phinc</login>
		<password><![CDATA[123]]></password>
	</employee>
<employee id="3">
		<first-name>irka</first-name>
		<last-name>fedort</last-name>
		<email>phinc@tut.by</email>
		<post>enginner</post>
		<login>phinc</login>
		<password><![CDATA[1]]></password>
	</employee>
<employee id="4">
		<first-name>irka</first-name>
		<last-name>fedort</last-name>
		<email>phinc@tut.by</email>
		<post>enginner</post>
		<login>phinc</login>
		<password><![CDATA[1]]></password>
	</employee>
<employee id="5">
		<first-name>ira</first-name>
		<last-name>skdnf</last-name>
		<email>1sakdfj@jkk.nhj</email>
		<post>1</post>
		<login>1</login>
		<password><![CDATA[1]]></password>
	</employee>
<employee id="6">
		<first-name>fdg</first-name>
		<last-name>employeech</last-name>
		<email>_kjf@jjk.nnn</email>
		<post>senior developer</post>
		<login>rty</login>
		<password><![CDATA[1]]></password>
	</employee>
<employee id="7">
		<first-name>Русские символы</first-name>
		<last-name>7</last-name>
		<email>mkyong.100@yahoo.com</email>
		<post>7</post>
		<login>7</login>
		<password><![CDATA[7]]></password>
	</employee>
<employee id="8">
		<first-name>7 employee</first-name>
		<last-name>swertbju</last-name>
		<email>mkyong.100@yahoo.com</email>
		<post>7</post>
		<login>7</login>
		<password><![CDATA[7]]></password>
	</employee>
<employee id="10">
		<first-name>Misha</first-name>
		<last-name>Kachanouski</last-name>
		<email>ghg@na.ty</email>
		<post>developer</post>
		<login>misha</login>
		<password><![CDATA[1]]></password>
	</employee>
<employee id="11">
		<first-name>ivan</first-name>
		<last-name>wert</last-name>
		<email>fff@hj.nn</email>
		<post>proger</post>
		<login>ivan1</login>
		<password><![CDATA[1]]></password>
	</employee>
<employee id="12">
		<first-name>Nadja</first-name>
		<last-name>Retsre</last-name>
		<email>ggg@jkl.bh</email>
		<post>re</post>
		<login>as</login>
		<password><![CDATA[2]]></password>
	</employee>
<employee id="13">
		<first-name>Denis</first-name>
		<last-name>dfg</last-name>
		<email>gj@ere.ng</email>
		<post>shgfdh</post>
		<login>s</login>
		<password><![CDATA[567]]></password>
	</employee>
<employee id="14">
		<first-name>Sanja</first-name>
		<last-name>Som</last-name>
		<email>s5@fr.tr</email>
		<post>senior developer</post>
		<login>som</login>
		<password><![CDATA[som]]></password>
	</employee>
<employee id="15">
		<first-name>Katja</first-name>
		<last-name>Trew</last-name>
		<email>jhjg@g.nj</email>
		<post>qwerty</post>
		<login>qwerty</login>
		<password><![CDATA[qwerty]]></password>
	</employee>
<employee id="16">
		<first-name>Pasha</first-name>
		<last-name>Gertyu</last-name>
		<email>dret@fgg.br</email>
		<post>disigner</post>
		<login>qw</login>
		<password><![CDATA[1]]></password>
	</employee>
</emp:employees>
